name: terceiroteste
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-257.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: UberMove
      fonts:
        - asset: fonts/UberMoveMedium.otf
  assets: 
    - assets/images/image-removebg-preview(1).png #aqui vai o endereço da logo da empresa, sendo necessaria a criação da pasta assets/image 
